#!/bin/bash
export OS_USERNAME=${OS_USERNAME_}
export OS_PASSWORD=${OS_PASSWORD_}
export OS_AUTH_URL=${OS_AUTH_URL_}
export OS_USER_DOMAIN_NAME=${OS_USER_DOMAIN_NAME_}
export OS_PROJECT_DOMAIN_NAME=${OS_PROJECT_DOMAIN_NAME_}
export OS_REGION_NAME=${OS_REGION_NAME_}
export OS_PROJECT_NAME=${OS_PROJECT_NAME_}
export OS_TENANT_NAME=${OS_TENANT_NAME_}
export OS_AUTH_VERSION=${OS_AUTH_VERSION_}
export OS_IDENTITY_API_VERSION=${OS_IDENTITY_API_VERSION_}
