#!/bin/bash
export OS_USERNAME=${OS_USERNAME}
export OS_PASSWORD=${OS_PASSWORD}
export OS_AUTH_URL="${OS_AUTH_URL}"
export OS_USER_DOMAIN_NAME="${OS_USER_DOMAIN_NAME}"
export OS_PROJECT_DOMAIN_NAME="${OS_PROJECT_DOMAIN_NAME}"
export OS_REGION_NAME="${OS_REGION_NAME}"
export OS_PROJECT_NAME="${OS_PROJECT_NAME}"
export OS_TENANT_NAME="${OS_TENANT_NAME}"
export OS_AUTH_VERSION=${OS_AUTH_VERSION}
export OS_IDENTITY_API_VERSION=${OS_IDENTITY_API_VERSION}
